### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#140]
- [x] kan vervangen worden voor NLDS `<Logo>` Component

- [x] checken/fixen: Logo in Safari is warped
- [ ] Logo kleur darkmode aanpassen (wit/grijs)
_1. aan Marwa vragen of ze hier tokens van wil toevoegen aan het Purmerend thema_

Config changes van Robbert zou dit mogelijk moeten maken:
- [ ] linken naar homepage of naar stap 1 van formulier? Deze keuze is aan Purmerend, ze kunnen dit in config zelf aanpassen. Voor nu: overleggen met Savi wat de meest toegankelijke keuze is. 
_1. linken naar purmerend.nl homepage + dit duidelijk in de begeleidende tekst omschreven. Bijv. terug naar de homepage van gemeente Purmerend._
_2. linken naar stap 1 van formulier + dit duidelijk in de begeleidende tekst omschrijven. Bijv: terug naar stap 1 van het meldingen formulier._

- [ ] Logo van de gemeente heeft een onvolledige alt tekst. Volgens NL Design System wil je hier bijvoorbeeld “Gemeente X logo, naar stap 1 - Beschrijf uw melding” https://nldesignsystem.nl/wcag/2.4.4/#fout-verkeerde-linktekst-voor-een-link-met-een-afbeelding
_1. alt tekst voor nu: logo gemeente Purmerend (check bij Savi of dit voldoende is)_
_2. alt tekst kan uitgebreider, kan Purmerend ook zelf in stellen in config. Bijv: Het logo van Purmerend: een schild en sterk gestileerde koeienkop die in elkaar overvloeien en een soort ketting vormen. Rechts hiervan staan boven elkaar gepositioneerd met gelijke tussenruimte de letters pur, mer, end._

**Comment by iehkaatee** [comment]
Kan het zijn dat dit allemaal al opgelost is met het implementeren van de prumerend styling en nieuwe componenten?
