### ISSUE TITLE
Fix: Link had geen font-family styling in Summary (stap 4)

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#169]
Zou gefixt moeten zijn met toegevoegde token in Purmerend theme. Is toegevoegd, komt mee bij het updaten van de Purmerend theme dependency.

**Comment by Robbert** [comment]
Wordt opgelost bij upgrade van design tokens package.

**Comment by justiandevs** [comment]
Opgelost.
