### ISSUE TITLE
Geselecteerde assets blijven bewaard

### ISSUE THREAD

**Issue by iehkaatee** [delta10/signalen-frontend-wcag#177]
voorbeeldscenario:

Wanneer je bij "lantaarn kapot" lantarens selecteert blijven die bewaard als je terug gaat naar stap 1 en vuurwerkoverlast intypt en daar objecten voor wilt selecteren

**Comment by justiandevs** [comment]
Dit is een vrij snelle fix, wat we eigenlijk moeten doen in stap 1 bij het zetten van de descriptie is selectedFeatures in de formState overschrijven naar een lege array op het moment dat de beschrijving niet is wat die in de ```prevState``` was.
