### ISSUE TITLE
Verbeterpunten rondom "dark mode", fonts en uitlijning

### ISSUE THREAD

**Issue by Ollie-nl** [delta10/signalen-frontend-wcag#179]
DarkMode geeft nog wat contract problemen

Vlakken zoals checkbox en spotlight geven grijze achtergrond met witte letters, die is niet goed te lezen voor de gebruikers. Dit lijken nu ook invoervelden textarea's.
Rode linkjes (taal kiezer) ook niet goed zichtbaar in DarkMode
Logo niet goed zichtbar in DarkMode
![image](https://github.com/user-attachments/assets/015c29bf-3e8a-491c-8659-369cfc0bb9c7)

![image](https://github.com/user-attachments/assets/00f30c30-aba4-4937-9673-aaaf19934100)

Op kleine schermen lijnt de kaart niet lekker uit, dit geeft een vreemde gap Bove de kaart
![image](https://github.com/user-attachments/assets/f6fe8912-007d-40b9-a745-7129d51c4d08)

"Wijzig contactgegevens" heeft een vreemd lettertype
![image](https://github.com/user-attachments/assets/bf9840ec-944c-4789-91b8-4c3fc8db1a75)

**Comment by justiandevs** [comment]
Punt met kaart uitlijnen opgepakt in #253. De rest van de issues zijn bekend en uitgewerkt in andere issues, daarmee ook dit issue gesloten om dubbele issues te voorkomen.
