### ISSUE TITLE
Utrecht textbox label (geen prio ivm backend)

### ISSUE THREAD

**Issue by Marwaxhello** [delta10/signalen-frontend-wcag#187]
Deze optie is (nu) niet mogelijk ivm backend. Evt. later toevoegen?

#

De kleurcontrast van de labeltekst is onvoldoende, zowel in de donkere als in de lichte mode. Savi en ik hebben dit probleem onderzocht en een mogelijke oplossing bedacht. Het idee is om ervoor te zorgen dat de text kleur zichtbare en (contrast) toegankelijke is, door onderstaande techniek te gebruiken (zie link).

* **Hoe het nu is: Onvoldoende contrast**

![Image](https://github.com/user-attachments/assets/c8e40a29-c0d9-4b0b-a7d5-8b8e41a0fe77)

* **Oplossing: Text kleur wit maken en uit de input halen**

![Image](https://github.com/user-attachments/assets/f742f875-912c-44e5-a1c7-b3660cf1df4b)

* **Methode**
https://nldesignsystem.nl/richtlijnen/formulieren/labels/zichtbare-naam/

**Comment by Robbert** [comment]
De placeholder-tekst heeft inmiddels voldoende contrast.
