### ISSUE TITLE
favicon toevoegen + configureerbaar maken

### ISSUE THREAD

**Issue by iehkaatee** [delta10/signalen-frontend-wcag#193]

**Comment by justiandevs** [comment]
In next moet de favicon.ico altijd direct in de /app directory geplaatst worden. Hier is weinig configureerbaar aan een voorbeeld PR: https://github.com/delta10/signalen-frontend-wcag/pull/198. 

Ik denk dat we in productie het best gewoon in de container van de gemeente dus een favicon.ico mounten (net zoals config.json) mounten naar het juiste pad? Wat vind jij hiervan @bartjkdp?

**Comment by bartjkdp** [comment]
@justiandevs het is prima als de default favicon `/favicon.ico` is, en het mounten op dit pad is op zich ook prima.

Maar we kunnen in de header toch ook gewoon:

```
<link rel="icon" href="<link>"/>
```

opnemen, om te verwijzen naar een favicon op een andere URL? Zou dit optioneel configureerbaar gemaakt kunnen worden? Met een fallback naar `/favicon.ico`?
