### ISSUE TITLE
Form filed checkbox Tailwind

### ISSUE THREAD

**Issue by Marwaxhello** [delta10/signalen-frontend-wcag#195]
Er zijn nog enkele Tailwind overwriting die de kleurwijziging verhinderen volgens mij.

`background-gray-200`  tailwind

![Image](https://github.com/user-attachments/assets/d20fd636-008c-4c62-af54-9edfd63c65b7)

**Comment by justiandevs** [comment]
Ik heb dit probleem opgelost met de volgende PR: https://github.com/delta10/signalen-frontend-wcag/pull/197
