### ISSUE TITLE
Logo Purmerend

### ISSUE THREAD

**Issue by Marwaxhello** [delta10/signalen-frontend-wcag#206]
- [ ] Logo kleur darkmode aanpassen (wit/grijs)

![Image](https://github.com/user-attachments/assets/37a347e4-9610-4260-98b1-3a901dab91e7)

https://purmerend.nl/ heeft in darkmode een wit/grijs logo. Is dit een SVG? 
Wat is hier het beste en snelste aanpak?

![Image](https://github.com/user-attachments/assets/5ce5739d-9134-4613-8bf6-37f49a5f8afc)

**Comment by justiandevs** [comment]
In de config bestaat er onder ```config.base.header.logo``` al de property ```dark_mode_url``` als deze gezet wordt naar de darkmode svg van Purmerend en dit asset in de ```public/assets``` map wordt gezet net zoals de rest van de logo's dan komt het helemaal goed ;)
