### ISSUE TITLE
Language Navigation color

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#214]
**Gevonden probleem:**

* Selected language rood geeft error vibes 

![Image](https://github.com/user-attachments/assets/70d26283-af16-45d7-8422-434351eb003c)

**Mogelijke oplossing:**
- volgens mij is er besloten dat de MVP alleen in Nederlands is, misschien dat de language switch er voor nu even uit kan? Of anders de kleur van selected language bijv. naar Purmerend groen veranderen? Dit zou zowel in darkmode als lightmode voldoende contrast moeten zijn. 

![Image](https://github.com/user-attachments/assets/2c630b5b-5da8-4557-a77d-17ef71e53e28)

**Comment by justiandevs** [comment]
Ik denk dat we deze functionaliteit net willen uitzetten voordat de tweede test periode aanbreekt :)
