### ISSUE TITLE
1.4.11 contrast focus ring light/darkmode + 2.4.7 consistency

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#215]
**Gevonden probleem 1.4.11:** 

De focusring van sommige interactieve elementen van het formulier heeft slecht contrast. Dit geldt zowel voor de Light als Dark modes van de pagina.

Voorbeeldp<img width="246" alt="Image" src="https://github.com/user-attachments/assets/0987bab3-7359-44a5-bfc0-35a3320d8ce5" />
agina: https://signalen-frontend-wcag.vercel.app/nl/incident

<img width="200" src="https://github.com/user-attachments/assets/09e1652e-3a28-4371-ae80-68c886fec83f">

**Mogelijke oplossing:**
- [ ] Focus visible tokens (of classname?) toevoegen/aanpassen op de elementen die nu default focus styling krijgen (lost ook gelijk 2.4.7 consistency en map focus op)

![Image](https://github.com/user-attachments/assets/1b383388-3d3d-4bde-bdd0-080bc501a8c1)

# 

**Gevonden probleem 2.4.7 :**

* Focus ring inconsistentie (in ieder geval in darkmode): twee verschillende soorten focus rings (wit dotted = vanuit NLDS? En solid wit/blauw vanuit React/Next of browser default?). 

| Default?    | NLDS? |
| -------- | ------- |
| <img width="200" src="https://github.com/user-attachments/assets/09e1652e-3a28-4371-ae80-68c886fec83f"> | <img width="200" src="https://github.com/user-attachments/assets/7039a344-0971-42c8-b109-b54395c74d86">  |

**Bij de volgende componenten komt dit probleem voor:**
* File upload
* Map (als deze focus moet krijgen - dit is misschien niet nodig zie issue:?)
* bepaalde textvelden (die niet utrecht componenten zijn)
* checkbox (stap 3 en stap 2 optionele questions)
#

* <img width="300" alt="Image" src="https://github.com/user-attachments/assets/b9219689-39cc-4fac-9b2e-43b2f8b90484" />

* <img width="246" alt="Image" src="https://github.com/user-attachments/assets/58393cdf-0126-4210-84c9-0de2054ed4fb" />

* <img width="300" alt="Image" src="https://github.com/user-attachments/assets/2ff60212-259c-4347-9996-63c68dccfbcb" />

**Mogelijk gerelateerd probleem:**

Bij stap 4 zou ik bij de “wijzig”link verwachten dat deze styling meekrijgt vanuit het Link component. Focus ring is niet dotted zoals bij andere NLDS comp. Ook reeds opgelost probleem met font family ging hier mis. Misschien omdat Link in een ander component zit? —> later checken of dit nog zo is (font family changes zijn ook nog niet zichtbaar in main)

**Comment by justiandevs** [comment]
Dit lijkt allemaal opgelost te zijn met verschillende issues die bij elkaar nu wel opgepakt zijn. Vandaar dit issue gesloten.
