### ISSUE TITLE
Zelfde font size heading/paragraph tekst (geen prio)

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#216]
**Gevonden probleem:**

Font size H2, label en Paragraph allemaal 20px? De ontbrekende visuele hiërarchie maakt het lastig om tekst te lezen en onderscheid te maken tussen het belang van bepaalde stukken tekst. 

<img width="300" src="https://github.com/user-attachments/assets/84797b3e-b2b6-49d4-b6ab-6e9227eb4ea6">

**Mogelijke oplossing:**

→ Savi gaat navragen aan Rian of het feit dat de info aanwezig is voldoende is voor AA in deze MVP is. If yes, dan evt. op een later moment als refactor task doen. Als het niet okay is dan zal er in het Purmerend thema wat aangepast moeten worden.

NB: [purmerend.nl](http://purmerend.nl/) maakt visueel wel onderscheid tussen Header en Paragraph font sizes.

**Comment by Robbert** [comment]
![Image](https://github.com/user-attachments/assets/396f0487-5ce3-450c-97f3-d82874c166af)

De purmerend website heeft het nog onoverzichtelijker:

- h1: 26px
- h2: 26px
- h3: 17.6px
- p: 20px

Wat mij betreft mag Purmerend de design tokens later zelf aanpassen. Ik heb geprobeerd contact te krijgen met de persoon die er over gaat bij Purmerend, maar die zag geen aanleiding om hierom kennis te maken.
