### ISSUE TITLE
1.4.10 & 4.1.2 | 400% zoom adres select

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#230]
**Gevonden probleem** 
Zoom in op de pagina (400%). Wanneer een adres wordt ingevoerd in het adresinvoerveld in Stap 2 van het formulier, kunnen de opties in het dropdown-menu niet volledig worden weergegeven (alleen de bovenste optie wordt getoond). Dit betekent dat een gebruiker mogelijk niet beseft dat er meer opties beschikbaar zijn in het dropdown-menu.

Overweeg om een symbool toe te voegen dat aangeeft dat er meer resultaten beschikbaar zijn in het dropdown-menu.

Voorbeeldpagina: https://signalen-frontend-wcag.vercel.app/nl/incident/vulaan

<img width="400" src="https://github.com/user-attachments/assets/f640b10b-052e-4dbd-a176-98737f2898a0">

**Mogelijke oplossing**
- [ ] Voeg een icon toe die de gebruiker een hint geeft dat er meer resultaten zijn (en plaats deze in een `<Icon>` component)

**Comment by Robbert** [comment]
dit is gefixt door https://github.com/delta10/signalen-frontend-wcag/pull/333/files
