### ISSUE TITLE
aria-required ontbreekt bij Radio Group

### ISSUE THREAD

**Issue by Robbert** [delta10/signalen-frontend-wcag#234]
Er staat wel "(verplicht)" in het label, maar `aria-required` is niet ingesteld

<img width="689" alt="Screenshot 2024-12-09 at 09 29 44" src="https://github.com/user-attachments/assets/fbf6beae-01c9-4e55-99a7-8ad8b1723037">

Dit is een bug in de Utrecht component, want de `required` prop wordt daar nog niet doorgegeven aan de `RadioButton`

- [x] bug daar fixen door `required` door te geven: https://github.com/nl-design-system/utrecht/blob/main/packages/components-react/radio-group-react/src/index.tsx#L90-L99
- [x] changeset toevoegen
- [x] PR mergen
- [x] release PR mergen
- [x] update installeren in deze repo
- [x] controle

**Comment by justiandevs** [comment]
https://github.com/nl-design-system/utrecht/pull/2670
