### ISSUE TITLE
1.3.1 "Vorige" button/link consistentie in styling

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#236]
**Gevonden probleem WCAG hertest:**

Er is een formulier op een webpagina met verschillende stappen. Om tussen de stappen te navigeren kan men verschillende links in het formulier gebruiken. Om naar de vorige stap te gaan, kan de gebruiker op de link "Vorige" klikken, zowel bovenaan als onderaan het formulier. Het probleem is dat beide links die naar dezelfde plaats gaan en dezelfde linktekst hebben, verschillend zijn vormgegeven: de ene ziet eruit als een link, de andere als een knop. Aangezien ze hetzelfde doen, zou ik aanbevelen dat ze dezelfde vormgeving krijgen.

Voorbeeldpagina: https://signalen-frontend-wcag.vercel.app/nl/incident/samenvatting

**Mogelijke oplossing**
- [ ] "Vorige" styling = De buttons hebben niet dezelfde styling, dat is verwarrend omdat ze hetzelfde doen. Het zou beter zijn links te gebruiken omdat je naar een andere pagina gaat.
- [ ] optioneel: als bovenstaande niet lukt kan ook de "Vorige" link bovenaan de pagina er helemaal uit halen

**Comment by justiandevs** [comment]
Is dit dezelfde issue als #224 ? Dan lijkt een van beide mij overbodig.
