### ISSUE TITLE
1.4.3 Focussed footer items contrast

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#238]
**Gevonden probleem:**

Het contrast van de tekst van sommige gefocuste elementen heeft niet genoeg contrast. Bijvoorbeeld de items in de footer.
Interactieve elementen moeten voldoende contrast behouden in alle toestanden, inclusief focustoestanden.

Voorbeeldpagina: https://signalen-frontend-wcag.vercel.app/nl/incident/contact

<img src="https://github.com/user-attachments/assets/b86c9f88-be8f-4b60-98a5-b3003690751d" width="500">

**Mogelijke oplossing:**
- [ ] purmerend thema tokens aanpassen (light en darkmode?)

**Comment by justiandevs** [comment]
Wordt opgelost met #194
