### ISSUE TITLE
3.3.1 & 3.3.2 verplichte elementen zijn niet "echt" verplicht

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#250]
Zie #234 

**Gevonden probleem:**
Er zijn verplichte elementen in Stap 2 van het formulier. Momenteel kan de gebruiker naar de volgende stap van het formulier gaan, zelfs als sommige van de verplichte invoervelden leeg zijn (Het invoerveld "Is het gevaarlijk?", en de radioknop "Waar gaat uw melding over?").

Formuliervalidatie moet indiening voorkomen wanneer verplichte velden leeg zijn en duidelijke foutmeldingen geven.

Voorbeeldpagina: https://signalen-frontend-wcag.vercel.app/nl/incident/vulaan

**Mogelijke oplossing:** Lost ook 3.3.2 op
- [ ] voeg formuliervalidatie toe: verplichte lege velden mogen niet leeg zijn bij "Volgende" of "Verstuur"
- [ ] zorg voor duidelijke foutmelding

**Comment by justiandevs** [comment]
Dit wordt opgelost met #234
