### ISSUE TITLE
Verbeteren foutafhandeling bij versturen

### ISSUE THREAD

**Issue by iehkaatee** [delta10/signalen-frontend-wcag#28]
Het kan bijvoorbeeld voorkomen dat de volgende fout optreed bij het versturen:

```
{"category":{"sub_category":["Ongeldige hyperlink - Object bestaat niet."]}}
```

Op dit moment wordt er niets gecommuniceerd naar de gebruiker.

**Comment by bartjkdp** [comment]
In principe zou dit niet moeten voorkomen, tenzij we een fout maken in het construeren van de URL van de categorie.

**Comment by iehkaatee** [comment]
Ik vind het ook prima om dit deels op te lossen via de retry knop. Maar nu is het in ieder geval zo dat als er iets fout gaat met de response dat de gebruiker niets te zien krijgt.
