### ISSUE TITLE
Refactor: kleurgerelateerde Tailwind classes (AdressCombobox)

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#299]
AdressCombobox.tsx heeft nog kleurgerelateerde Tailwind classes

<img width="667" alt="Image" src="https://github.com/user-attachments/assets/325b37f6-20c5-4088-8755-101225bcb03a" />

# 

- [ ] project nalopen of dit op andere plekken ook nog het geval is

**Comment by iehkaatee** [comment]
wordt waarschijnlijk opgelost met https://github.com/delta10/signalen-frontend-wcag/pull/323
