### ISSUE TITLE
Errormelding "Mijn locatie" MapDialog

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#301]
**Before:** 
<img width="2025" alt="Image" src="https://github.com/user-attachments/assets/1d8267bd-eb9c-4bf7-a3fd-72b48660e1f6" />

* Error melding bij geen toestemming “Mijn locatie” is nu langgerekt? ✅ (fixed by [PR#321](https://github.com/delta10/signalen-frontend-wcag/pull/321))
* het contrast van deze Alert/Error is niet voldoende (check: al opgelost met thema changes?) ✅ fixed by [PR#321](https://github.com/delta10/signalen-frontend-wcag/pull/321) : luistert nu naar alert kleur van utrecht = purmerend white-1)

**After:**
<img width="1336" alt="Image" src="https://github.com/user-attachments/assets/2db4ef67-ba00-4f94-a610-30ea1cf3c262" />

**Comment by justiandevs** [comment]
Ter info: In dark mode lijkt het contrast issue wel opgelost te zijn. In light mode nog niet.
