### ISSUE TITLE
MapDialog "Objecten" verzamelissue

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#302]
## Probleem 

1. De melding "zoom in om de objecten te zien" is er ook wanneer er geen objecten zijn 
<img width="340" alt="Image" src="https://github.com/user-attachments/assets/346d6427-4aaf-49a5-9f38-ab173fa7dd0c" />

2. Wat zijn “de objecten”? Als ik niet weet dat dit bijv. lantarenpalen zijn, blijf ik dan inzoomen? Of denk ik dat de straatnamen/huizen etc de objecten zijn waar ik naar moet inzoomen?

https://github.com/delta10/signalen-frontend-wcag/issues/329

4. Wanneer een adres gekozen is, blijft de button tekst “Ga verder zonder object”. Verwarrend, want ik heb toch een adres gekozen? Dit heeft niets te maken met objecten. Ik zou deze button tekst verwachten bij de straatverlichting, waar het mogelijk is om een object op de kaart te selecteren. 
<img width="500" alt="Image" src="https://github.com/user-attachments/assets/e12353c6-00ea-4344-8e47-7e5b318ce404" />
Bij straatverlichting + object geselecteerd is dit wel netjes en duidelijk (button tekst: “Meld deze straatverlichting”)

5. (was 6) wanneer je geen object geselecteerd hebt, bij straatverlichting blijft de button tekst “Ga verder zonder object”. Is het duidelijk genoeg dat je de melding wel kunt doen obv alleen een adres en geen lamp hoeft te selecteren. 

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/b2640bcf-0e14-4f88-af13-e8a528f43c66" />

### Mogelijke oplossing 

* de "objecten" melding alleen laten zien als er sprake is van objecten?
* wellicht ook een optie om bij straatverlichting te benoemen dat het nummer van de lantarenpaal op de paal staat?
* uitleg over wat objecten zijn (in de accordion bijv)?

**Comment by justiandevs** [comment]
wellicht ook een optie om bij straatverlichting te benoemen dat het nummer van de lantarenpaal op de paal staat?

@bartjkdp zie jij hier een optie toe? Wij zijn niet zo snel mogelijkheden om dit te kunnen bewerkstelligen. En hoe zou dit gaan met niet alleen lantarnpalen, maar bijv een bomen of vuilbak selecteerlaag?
