### ISSUE TITLE
Form flow (bijv. 2x Stap 1)

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#303]
- [x] Soms na invullen van het verplichte veld in stap 1 en op volgende klikken, kom ik nogmaals op stap 1 en is mijn ingevoerde informatie weg?

- [x] Tabvolgorde is soms anders (depending on cookies/refresh?) - Bijv. upload of an image click "Volgende", focus takes me to the next upload area for a second picture. This is whether the panel listing the name of the uploaded file is open or closed Refreshing the form fixed the issue

- [x] Radiobuttons blokkeren soms de flow (alsof hij een oude errormessage onthoud ook als je een andere option aanklikt?) 

- [x] Soms komen error messages op onverwachte momenten (bijv. al voor je op "Volgende" klikt)

- [x] Soms zijn "Volgende" buttons disabled op momenten dat je het niet verwacht

- [ ] Soms geen objecten op kaart te zien (bijv. eerst keywoord vuurwerk in stap 1, terug, daarna lamp = geen objecten te zien of soms pas nadat je een adres geselecteerd hebt en daarna inzoomt op de kaart)

**Comment by iehkaatee** [comment]
> "Soms zijn "Volgende" buttons disabled op momenten dat je het niet verwacht" Dit gebeurd alleen wanneer je bij stap 2 bij de radio button de opties aanvinkt die een error aangeven. Als je dit heb gedaan en dan weer naar stap 1 staan al je buttons (volgende buttons) op disabled mode en een refresh fixed dit issue niet...
> 
> Waar gaat dit fout? wat is hier de fix voor? Ik denk dat als je ergens de error optie kiest gaat de hele website op error/disabled mode staan en als je dit niet fixed (een andere optie met geen error kiest) en meteen naar vorige gaat staat je website nog steeds op error. Dit is ergens ingesteld en er moet ergens dan worden ingesteld dat de refresh helemaal van begin start weer en je laatste info niet meeneemt of laatste staat?

Dit zou als het goed is opgelost moeten zijn met: https://github.com/delta10/signalen-frontend-wcag/pull/320

**Comment by Marwaxhello** [comment]
"Soms geen objecten op kaart te zien (bijv. eerst keywoord vuurwerk in stap 1, terug, daarna lamp = geen objecten te zien of soms pas nadat je een adres geselecteerd hebt en daarna inzoomt op de kaart)"
Ik denk dat dit gebeurd omdat het nog denkt dat je op vuurwerk staat... want dit gebeurd alleen als je bijvoorbeeld heel snel wat invult en dan volgende en dan weer terug en dan lamp invult en dan volgende dan heeft het een soort glitch of zo dat het de straatverlichting objecten niet aangeeft.

Waaneer hoor je de objecten te zien? meteen als je de kaart in gaat of moet je eerst in zoemen? (Het beste is om ze meteen te zien) Als ik alle stappen vanaf begins af aan goed volg en "lamp" invoer dan op de kaart click zie ik geen objecten, ik moet drie keer in zoemen voordat ik wat zie... Hoort dit?
