### ISSUE TITLE
Verschil border radius/padding focusring "Volgende" en "Vorige" button

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#304]
## Probleem 

De border radius van de navigatie buttons/links verschillen (link = vierkant, buttons = ronder)
* In light en darkmode

| Button    | Link |
| -------- | ------- |
| <img width="262" alt="Image" src="https://github.com/user-attachments/assets/5909b4b8-7c27-4077-93f5-9b654076add1" />  | <img width="286" alt="Image" src="https://github.com/user-attachments/assets/8e98a000-73a8-4dc2-96b1-611bddfe762e" /> |

Ook heeft niet iedere button dezelfde padding.
<img width="183" alt="Image" src="https://github.com/user-attachments/assets/f1322acc-0d4b-47a6-b3d1-6344ca39380b" />

**Comment by Robbert** [comment]
Gefixt door https://github.com/nl-design-system/utrecht/pull/2683
