### ISSUE TITLE
Contrast tekst input (Stap 3 - darkmode)

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#308]
Wanneer je bij stap 3 invalid telefoonnummer en/of email adres invoert en op volgende drukt, is de tekst in het invoerveld niet meer zichtbaar omdat het invoerveld opeens een witte achtergrond heeft gekregen.

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/01517c6c-5517-4c00-ab88-0b537866ee3f" />

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/87144cc4-443e-4941-bf24-29c0fd23174b" />

**Comment by Robbert** [comment]
Gefixt in https://github.com/delta10/signalen-frontend-wcag/pull/338

![Screenshot 2024-12-27 at 12 30 54](https://github.com/user-attachments/assets/9475d05f-6a18-4b9c-97b8-85c9d0f9c17a)

**Comment by Robbert** [comment]
![Screenshot 2024-12-27 at 12 31 56](https://github.com/user-attachments/assets/caa8208b-3e65-4d7a-8d7d-c112508c8def)
