### ISSUE TITLE
MapDialog accordion niet keyboard toegankelijk

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#312]
## Probleem

* Scrollen door de map instructies is momenteel alleen mogelijk met de muis, arrow key's doen het niet. Een keyboard gebruiker kan de keyboard instructies dus niet middels het keyboard bereiken. 

* wanneer de instructie accordion open is en je door de objecten lijst tabt, verschuift het scherm niet mee met de getabte objecten. Je blijft verder gaan in de lijst met lampen, en dit zie je op de kaart, maar het side paneel laat dit niet zien. Dit kan de tabvolgorde verwarrend maken voor mensen die dit paneel gebruiken.

**Comment by Yolijn** [comment]
Deze is gisteren opgelost, alleen zie je nog niet welke option `active` is. Dat wordt opgelost met het nieuwe thema die @Robbert aan het maken is.
