### ISSUE TITLE
Placeholder input field contrast lightmode

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#313]
## Gevonden probleem

Onvoldoende contrast background color input field en de placeholder tekst in lightmode:
<img width="452" alt="Image" src="https://github.com/user-attachments/assets/0fa6d9ad-30da-4017-9887-cc9de5f9a971" />

## Mogelijke oplossing
- [ ] check: is dit opgelost door eerdere theme changes? (of is toen alleen voor darkmode gekeken)

**Comment by Robbert** [comment]
Contrast is gefixt inmiddels, is nu [4,58 ÷ 1](https://nldesignsystem.nl/contrast/?background-color=rgb%28244%2C+245%2C+246%29&color=rgb%28112%2C+111%2C+111%29)
