### ISSUE TITLE
Alert Dialog in MapDialog (400% Zoom)

### ISSUE THREAD

**Issue by TessaViergever** [delta10/signalen-frontend-wcag#336]
Draft [PR#335 ](https://github.com/delta10/signalen-frontend-wcag/pull/335)

#
**Probleem:** MapDialog Alert Dialog "Mijn locatie"

Is het in deze alert dialog ook mogelijk om automatisch de viewport te verschuiven naar het element dat focus krijgt (in dit geval de sluitknop van de alert)? 

Wanneer ik op 400% zoom ben en door de MapDialog tab en via "Mijn locatie" (geen toestemming) bij deze alert kom, krijg ik de "Sluit melding" button niet in beeld. Als ik op enter druk, sluit de Alert wel dus de focus is wel op de "Sluit melding" button (maar ik weet dat dit zo werkt, een bezoeker waarschijnlijk niet). Als ik door tab in plaats van op enter druk, kom ik niet meer terug op de pagina content en kan ik alleen weg door op esc te drukken (en daarmee sluit ik dan gelijk de hele MapDialog).

<img width="1454" alt="Scherm­afbeelding 2024-12-23 om 11 53 07" src="https://github.com/user-attachments/assets/880caca4-ee3b-471a-aeb1-f41d28c32b33" />

Bij alle andere elementen op de pagina verschuift de viewport wel mee naar het element dat focus heeft. 

**Mogelijke oplossing:**

* margin styling op dialog verwijderen/aanpassen?
* overflow scrol (staat erop - zou het moeten doen?) 
* AlertDialog Component van Utrecht gebruiken? -> is al een Alert Dialog
* misschien gaat het mis omdat het een Alert Dialog binnen een Dialog is?

**Comment by MeesoPost** [comment]
# Dialog probleem dubieuze oplossingen

## Wat was er mis?
De Alert Dialog had een te grote margin waardoor de 'Sluiten' knop uit beeld verdween. Ook nam het teveel ruimte in bij 400% zoom. de max-inline-block weghalen hielp voor een deel maar je kon alsnog niet ver genoeg scrollen voor de button

## Wat heb ik geprobeerd?
- Tailwind margins van 128px naar 16px veranderd maar dat ging niet goed met de ux.
- Max-width gezet op 600px zodat de dialog over de "Mijn locatie" button valt omdat je die toch niet nodig hebt

# before
![Image](https://github.com/user-attachments/assets/ceac7537-5337-4bd8-a60d-ef9a47522251)
# after
![Image](https://github.com/user-attachments/assets/75e3b81e-5568-4c24-9f2c-6b5fd47da2d6)

# before:

![Image](https://github.com/user-attachments/assets/fa565446-0be3-47ea-8492-9d5e5f8890f2)


# after: met maxWidth: '600px'
![Image](https://github.com/user-attachments/assets/7f47c0c1-c1d3-4fa1-8608-6ac8c37a8dd2)

## nu heb ik het gedaan door de maxWidth 100px te maken en de margin 16px
![Image](https://github.com/user-attachments/assets/052032c8-39ea-4eaa-9982-a127c48cb0bd)

# nu ziet het er zo uit als max-inline-block uitstaat
![Image](https://github.com/user-attachments/assets/4a42634d-4355-4186-b9cc-1ad71c441f6e)
![Image](https://github.com/user-attachments/assets/f2020401-1d2c-4402-a208-8d478be48ffa)
