### ISSUE TITLE
Loading state en spinner toevoegen bij elke stap

### ISSUE THREAD

**Issue by iehkaatee** [delta10/signalen-frontend-wcag#59]
Via dit issue willen we graag bij houden wanneer de pagina geladen is in een loading state en wanneer deze op true staat iets van een spinner tonen.

Dit is nu eigenlijk alleen lokaal echt een 'probleem' want in deze omgeving duurt de eerste keer laden van de volgende stap wat lang omdat het prefatchen nog niet werkt. Maar los daarvan zou het wel netjes zijn om dit sowieso geimplementeerd te hebben mocht om wat voor reden het ophalen van de volgende stap wat vertraagd zijn dan krijgt te gebruiker niet een rare layout shift te zien.

**Comment by justiandevs** [comment]
Ja, ik denk dat het ook slim is om deze loading state om de gehele pagina heen te "wrappen". Dit om dan alsnog te voorkomen dat bijv de (nieuwe) stepper een layout shift krijgt.

**Comment by justiandevs** [comment]
https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming Dit is interessant om te lezen, wij werken dan eigenlijk niet met een scenario waarin je dit zou toepassen (met server components) maar wellicht wel interessant om is door te nemen.
