### ISSUE TITLE
Als gebruiker wil ik kunnen zoeken op adres bij het selecteren van een punt op de kaart

### ISSUE THREAD

**Issue by bartjkdp** [delta10/signalen-frontend-wcag#8]
Dit doen we met behulp van de PDOK locatieserver. We limiteren de zoekresultaten tot een specifieke gemeente.

**Comment by justiandevs** [comment]
Op dit moment heb ik het volgende gerealiseerd; een PDOK api call via de "Address" service, om op basis van een gemeentenaam (gespecifieerd in configuration.json) en search query een call te doen naar PDOK suggest api.

Integratie met de kaart en combobox wacht ik even voor; eerst moet er een goed combobox alternatief wat gebruikersvriendelijk is beschikbaar komen.

**Comment by bartjkdp** [comment]
Het is prima om te wachten met de combobox. Ik denk wel dat we het state management alvast kunnen maken. Dus als je een stukje adres invult in een input veld, dat we voor nu een heel simpel lijstje tonen (ul) met buttons je op kan klikken. Als je klikt op de button dan gaat de kaart direct naar het adres en wordt de pin gezet.
