### ISSUE TITLE
Formulieren stylen

### ISSUE THREAD

**Issue by justiandevs** [delta10/signalen-frontend-wcag#84]
Zowel in stap 1, 2 als 3 heeft niet elke Fieldset dezelfde styling, dit ziet er soms raar uit. Niet alle elementen staan even ver uit elkaar, zowel binnen de Fieldsets als de Fieldsets zelf, als we dit fixen zit het mbt tot Form styling denk ik wel prima.

**Comment by iehkaatee** [comment]
Bevindingen van vergelijken met huidige signalen frontend:

1. De footer ontbreekt nu nog:
<img width="1410" alt="image" src="https://github.com/user-attachments/assets/4b1f7582-9263-424d-9a18-bbb092a63b27">

2.

**Comment by iehkaatee** [comment]
Feedback van Bart voor administratie:
Footer is inderdaad belangrijk, met links naar Privacy statement en Toegankelijkheid. Dat zijn externe links.
Ik vind het niet zo erg als het iets anders uitziet, dus dit hoeft niet van mij.
Button hoeft niet overgenomen worden. Ik vind onze button beter.
Alert hoeft niet overgenomen te worden.
Deze melding hoeft niet op andere pagina's wat mij betreft.
Ik vind het nu, beter dat het expliciet is wat verplicht en niet verplicht is.
Hoeft niet, als foutmeldingen per veld (zoals we nu hebben) voldoende toegankelijk is. Ik vind het eigenlijk wel fijn dat je nu maar op één plek hoeft te kijken.
Sluit knop is nodig inderdaad.
Ik denk dat gegroepeerd inderdaad duidelijker is, kan me voorstellen dat mensen nu meer moeten zoeken naar "Gebruik deze locatie"
Dit komt vanuit het NL design system en kan ingesteld worden met tokens, dus hoeft wat mij betreft niet.
De oude foutmelding vind ik beter, lijkt me goed om die over te nemen.
Deze zou ik ook graag terugzien.
Meldingsnummer is is inderdaad belangrijk, deze moeten we weer tonen.
De knop onder het formulier vind ik inderdaad beter dan de knop naast het formulier. Dit mag ook een primaire actie zijn. Ik zou de tekst veranderen naar "Doe nog een melding".

**Comment by iehkaatee** [comment]
Ik ga issues aanmaken voor de openstaande punten zodat ze opgepakt kunnen worden
